import { createAsyncThunk, createSlice, current } from "@reduxjs/toolkit";

const initialState = {
  catCategories: [],
  catImages: [],
  status: "",
  imagesStatus: "",
  imageBrowsingStatus: "",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getCatsCategories = createAsyncThunk(
  "cats/categories",
  async () => {
    const categories = await fetch(
      "https://api.thecatapi.com/v1/categories"
    ).then((res) => res.json());
    // The value we return becomes the `fulfilled` action payload
    return categories;
  }
);

export const getImagesByCategory = createAsyncThunk(
  "byCategory/images",
  async (category) => {
    const images = await fetch(
      `https://api.thecatapi.com/v1/images/search?limit=10&page=1&category_ids=${category}`
    ).then((res) => res.json());
    return images;
  }
);

export const getCatsImages = createAsyncThunk("cats/images", async () => {
  const images = await fetch(
    "https://api.thecatapi.com/v1/images/search?limit=10&page=1&category_ids=1"
  ).then((res) => res.json());
  return images;
});

export const browseMoreImages = createAsyncThunk(
  "browse/images",
  async (page) => {
    const browsedImages = await fetch(
      `https://api.thecatapi.com/v1/images/search?limit=10&page=${page}&category_ids=1`
    ).then((res) => res.json());
    return browsedImages;
  }
);

export const catsSlice = createSlice({
  name: "counter",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Use the PayloadAction type to declare the contents of `action.payload`
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCatsCategories.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getCatsCategories.fulfilled, (state, action) => {
        state.status = "fullfilled";
        state.catCategories = action.payload;
        console.log(state.catCategories);
      })

      .addCase(getCatsImages.pending, (state) => {
        state.imagesStatus = "loading";
      })
      .addCase(getCatsImages.fulfilled, (state, action) => {
        state.imagesStatus = "fullfilled";
        state.catImages = action.payload;
      })

      .addCase(browseMoreImages.pending, (state) => {
        state.imageBrowsingStatus = "loading";
      })
      .addCase(browseMoreImages.fulfilled, (state, action) => {
        state.imageBrowsingStatus = "fullfilled";
        console.log(...current(state).catImages);
        state.catImages = [...current(state).catImages, ...action.payload];
      })

      .addCase(getImagesByCategory.pending, (state) => {
        state.imageBrowsingStatus = "loading";
      })
      .addCase(getImagesByCategory.fulfilled, (state, action) => {
        state.imageBrowsingStatus = "fullfilled";
        state.catImages = action.payload;
      });
  },
});

export const { incrementByAmount } = catsSlice.actions;

export default catsSlice.reducer;
